uploads = []
generated = []

[[outputs]]
id = "nyiujf8jei7cazH_MbRHL"
uri = "file://lolo_cd_output.mp3"
type = "audio"
title = "nepe flacido flacido"

[[outputs]]
id = "rJMdOMIsKnB3_HGdkQHht"
uri = "file://lolo_cd_voz.mp3"
type = "audio"
title = "nepe flacido flacido - Diever (es-CO)"
